version: '3'
services:
  client:
    build: ./src/client
    volumes:
      - ./src/client:/client
      - /client/node_modules
    ports:
      - 3000:3000
    container_name: teahouse_client
    depends_on:
      - server
  server:
    build: ./src/server
    volumes:
      - ./src/server:/server
      - /server/node_modules
    ports:
      - 8000:8000
    container_name: teahouse_server
    depends_on:
      - mongo
      - redis
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=production
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
      - ./logs:/log/logs
    ports:
      - "27017:27017"
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379